require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - public/**/*
    - tmp/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - !ruby/regexp /old_and_unused\.rb$/
  RunRailsCops: true

Debugger:
  Enabled: false

EndAlignment:
  Enabled: false

BlockAlignment:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

UnlessElse:
  Enabled: false

CaseIndentation:
  Enabled: false

SingleLineMethods:
  Enabled: false

TrailingComma:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false
