require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - public/**/*
    - uploads/**/*
    - tmp/**/*
    - features/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - !ruby/regexp /old_and_unused\.rb$/
    - persistent/auto_responder_paper_data.rb
  RunRailsCops: true

RSpec/DescribedClass:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Style/Documentation:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/Lambda:
  Enabled: false
