language: ruby
cache: bundler
rvm:
  - 2.1.1

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

services:
  - redis-server

before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'create database sapphire_test'
  - psql -c 'create database sapphire_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:setup
  - RAILS_ENV=test bundle exec sidekiq -d -L /tmp/sidekiq.log

script:
  - bundle exec rspec spec
  - bundle exec cucumber
