os: linux
dist: xenial
language: ruby

notifications:
  email: false

addons:
  chrome: stable

cache:
  bundler: true

rvm:
  - 2.6.5

env:
  global:
    - RAILS_ENV=test
    - COVERAGE=true
  - DB=sqlite
  - DB=postgresql

os: linux
dist: xenial

services:
  - postgresql
  - xvfb

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate

script:
  - DISPLAY=:99.0 && bundle exec rspec
