language: ruby

notifications:
  email: false

cache:
  bundler: true
  directories:
  - $HOME/travis_phantomjs

sudo: false

rvm:
  - 2.1.6 # current production
  - 2.3.8

env:
  - DB=sqlite
  - DB=postgresql

before_script:
  - set -eux;
    export PHANTOMJS_VERSION=2.1.1;
    phantomjs --version;
    export PATH=$HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH;
    phantomjs --version;
    if [ "$(phantomjs --version)" != "$PHANTOMJS_VERSION" ]; then
      rm -rf $HOME/travis_phantomjs;
      mkdir -p $HOME/travis_phantomjs;
      if [ ! -f $HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 ]; then
        travis_retry wget
          https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
          -O $HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2;
      fi;
      tar -xvf
        $HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
        -C $HOME/travis_phantomjs;
    fi;
    phantomjs --version;
    set +eux
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database sapphire_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:test:prepare

script:
  - COVERAGE=true bundle exec rspec spec
