require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EvaluationsController do

  # This should return the minimal set of attributes required to create a valid
  # Evaluation. As you add validations to Evaluation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EvaluationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all evaluations as @evaluations" do
      evaluation = Evaluation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:evaluations).should eq([evaluation])
    end
  end

  describe "GET show" do
    it "assigns the requested evaluation as @evaluation" do
      evaluation = Evaluation.create! valid_attributes
      get :show, {:id => evaluation.to_param}, valid_session
      assigns(:evaluation).should eq(evaluation)
    end
  end

  describe "GET new" do
    it "assigns a new evaluation as @evaluation" do
      get :new, {}, valid_session
      assigns(:evaluation).should be_a_new(Evaluation)
    end
  end

  describe "GET edit" do
    it "assigns the requested evaluation as @evaluation" do
      evaluation = Evaluation.create! valid_attributes
      get :edit, {:id => evaluation.to_param}, valid_session
      assigns(:evaluation).should eq(evaluation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Evaluation" do
        expect {
          post :create, {:evaluation => valid_attributes}, valid_session
        }.to change(Evaluation, :count).by(1)
      end

      it "assigns a newly created evaluation as @evaluation" do
        post :create, {:evaluation => valid_attributes}, valid_session
        assigns(:evaluation).should be_a(Evaluation)
        assigns(:evaluation).should be_persisted
      end

      it "redirects to the created evaluation" do
        post :create, {:evaluation => valid_attributes}, valid_session
        response.should redirect_to(Evaluation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved evaluation as @evaluation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluation.any_instance.stub(:save).and_return(false)
        post :create, {:evaluation => {  }}, valid_session
        assigns(:evaluation).should be_a_new(Evaluation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluation.any_instance.stub(:save).and_return(false)
        post :create, {:evaluation => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested evaluation" do
        evaluation = Evaluation.create! valid_attributes
        # Assuming there are no other evaluations in the database, this
        # specifies that the Evaluation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Evaluation.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => evaluation.to_param, :evaluation => { "these" => "params" }}, valid_session
      end

      it "assigns the requested evaluation as @evaluation" do
        evaluation = Evaluation.create! valid_attributes
        put :update, {:id => evaluation.to_param, :evaluation => valid_attributes}, valid_session
        assigns(:evaluation).should eq(evaluation)
      end

      it "redirects to the evaluation" do
        evaluation = Evaluation.create! valid_attributes
        put :update, {:id => evaluation.to_param, :evaluation => valid_attributes}, valid_session
        response.should redirect_to(evaluation)
      end
    end

    describe "with invalid params" do
      it "assigns the evaluation as @evaluation" do
        evaluation = Evaluation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluation.any_instance.stub(:save).and_return(false)
        put :update, {:id => evaluation.to_param, :evaluation => {  }}, valid_session
        assigns(:evaluation).should eq(evaluation)
      end

      it "re-renders the 'edit' template" do
        evaluation = Evaluation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Evaluation.any_instance.stub(:save).and_return(false)
        put :update, {:id => evaluation.to_param, :evaluation => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested evaluation" do
      evaluation = Evaluation.create! valid_attributes
      expect {
        delete :destroy, {:id => evaluation.to_param}, valid_session
      }.to change(Evaluation, :count).by(-1)
    end

    it "redirects to the evaluations list" do
      evaluation = Evaluation.create! valid_attributes
      delete :destroy, {:id => evaluation.to_param}, valid_session
      response.should redirect_to(evaluations_url)
    end
  end

end
