require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RatingGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # RatingGroup. As you add validations to RatingGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RatingGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rating_groups as @rating_groups" do
      rating_group = RatingGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rating_groups).should eq([rating_group])
    end
  end

  describe "GET show" do
    it "assigns the requested rating_group as @rating_group" do
      rating_group = RatingGroup.create! valid_attributes
      get :show, {:id => rating_group.to_param}, valid_session
      assigns(:rating_group).should eq(rating_group)
    end
  end

  describe "GET new" do
    it "assigns a new rating_group as @rating_group" do
      get :new, {}, valid_session
      assigns(:rating_group).should be_a_new(RatingGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested rating_group as @rating_group" do
      rating_group = RatingGroup.create! valid_attributes
      get :edit, {:id => rating_group.to_param}, valid_session
      assigns(:rating_group).should eq(rating_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RatingGroup" do
        expect {
          post :create, {:rating_group => valid_attributes}, valid_session
        }.to change(RatingGroup, :count).by(1)
      end

      it "assigns a newly created rating_group as @rating_group" do
        post :create, {:rating_group => valid_attributes}, valid_session
        assigns(:rating_group).should be_a(RatingGroup)
        assigns(:rating_group).should be_persisted
      end

      it "redirects to the created rating_group" do
        post :create, {:rating_group => valid_attributes}, valid_session
        response.should redirect_to(RatingGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rating_group as @rating_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        RatingGroup.any_instance.stub(:save).and_return(false)
        post :create, {:rating_group => {  }}, valid_session
        assigns(:rating_group).should be_a_new(RatingGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RatingGroup.any_instance.stub(:save).and_return(false)
        post :create, {:rating_group => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rating_group" do
        rating_group = RatingGroup.create! valid_attributes
        # Assuming there are no other rating_groups in the database, this
        # specifies that the RatingGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RatingGroup.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => rating_group.to_param, :rating_group => { "these" => "params" }}, valid_session
      end

      it "assigns the requested rating_group as @rating_group" do
        rating_group = RatingGroup.create! valid_attributes
        put :update, {:id => rating_group.to_param, :rating_group => valid_attributes}, valid_session
        assigns(:rating_group).should eq(rating_group)
      end

      it "redirects to the rating_group" do
        rating_group = RatingGroup.create! valid_attributes
        put :update, {:id => rating_group.to_param, :rating_group => valid_attributes}, valid_session
        response.should redirect_to(rating_group)
      end
    end

    describe "with invalid params" do
      it "assigns the rating_group as @rating_group" do
        rating_group = RatingGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RatingGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => rating_group.to_param, :rating_group => {  }}, valid_session
        assigns(:rating_group).should eq(rating_group)
      end

      it "re-renders the 'edit' template" do
        rating_group = RatingGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RatingGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => rating_group.to_param, :rating_group => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rating_group" do
      rating_group = RatingGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => rating_group.to_param}, valid_session
      }.to change(RatingGroup, :count).by(-1)
    end

    it "redirects to the rating_groups list" do
      rating_group = RatingGroup.create! valid_attributes
      delete :destroy, {:id => rating_group.to_param}, valid_session
      response.should redirect_to(rating_groups_url)
    end
  end

end
