name: "Run Test Suite"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6.8, 2.7.4]
        db: ["postgres", "sqlite"]
    services:
      postgres:
        image: postgres:10.15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test

      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

      DB: "${{ matrix.db }}"

    steps:
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: "Install Bundler"
        run: "gem install bundler:1.17.3"

      - uses: actions/checkout@v2

      - name: "Setup bundler cache"
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp config/database.yml.github config/database.yml
          cp config/mail.yml.github config/mail.yml
          bundle exec rake db:create
          bundle exec rake db:migrate

      - name: Run specs
        run: bundle exec rspec
